### ISSUE TITLE
What is the license of the FoLiA data format?

### ISSUE THREAD

**Issue by luutuntin** [proycon/folia#103]
Hi Maarten,

I am citing the FoLiA format in my paper, which requires its license information. I suppose that license must be different from the GNU General Public License v3.0 of the GitHub source code. But I cannot find it in [your documentation](http://foliapy.readthedocs.io/en/latest/?badge=latest). Can you give me a hint?

Best,
Alex

**Comment by proycon** [comment]
Hi Alex, the format and specification itself is also just GPL v3

**Comment by luutuntin** [comment]
One anonymous reviewer of my paper mentioned that a data format cannot be licensed under the GNU GPL (without further elaboration). 
These Wikipedia articles seem relevant:

- https://en.wikipedia.org/wiki/Open_file_format
- https://en.wikipedia.org/wiki/List_of_open_file_formats

Should I say that FoLiA is an open file format, implemented by open (GPL v3) source code?

**Comment by proycon** [comment]
Yes, we're definitely an open file format, so the way you formulated it sounds fine to me. The specification and documentation is all generated by GPLv3 code, so technically anybody is free to fork it and do with it whatever they want (preserving the license). I kind of see what the reviewer meant but never gave that too much thought yet (and nobody asked before). As an open format, people may even write FoLiA parsers and serialisers, etc, that are not GPLv3 (even proprietary ones if the code is not directly derived, as much as I'd dislike that).

**Comment by luutuntin** [comment]
Thank you.
