### ISSUE TITLE
Question: why can't corrections have features?

### ISSUE THREAD

**Issue by mhkuu** [proycon/folia#2]
Corrections can't have features (`folia.Feature`) at the moment. I'm not entirely sure why this isn't allowed, would you care to elaborate? 

Reason why I'm asking is that we're compiling a learner corpus which is annotated with corrections that are classified with a specific unit, problem and part-of-speech; e.g. `[roed/roet]SPE*I*N` signals there's a spelling error (SPE) in the word 'roed' (correctly: roet), it is incorrectly (I) spelled noun (N). I'd like to split these features s.t. I'll later be able to query on them. So e.g.

        <w xml:id="example.text.1.p.1.s.5.w.6">
          <correction class="SPE">
            <new>
              <t>roet</t>
            </new>
            <original auth="no">
              <t>roed</t>
            </original>
            <feat class="I" subset="problem"/>
            <feat class="N" subset="pos"/>
          </correction>
        </w>

But this is not allowed by the `foliavalidator` currently :-) Other ideas for a proper solution are also welcome. Thanks very much in advance!

**Comment by proycon** [comment]
Right, this indeed sounds like a perfectly valid strategy. Perhaps it was an oversight to not have allowed `Feature` in `Correction`. I will add it.

**Comment by proycon** [comment]
Should work now, please reopen if not :)
