### ISSUE TITLE
Feature request: easy way to see the statistics of a file (e.g., number of annotated MWE)

### ISSUE THREAD

**Issue by kercos** [proycon/folia#20]

**Comment by proycon** [comment]
I just tested this, and although a bit crude, the ``foliacount`` tool can already do this:

```
$ foliacount -t entity example.xml
Processing example.xml
Counted example.xml
entity	6
documents   1
```

It doesn't distinguish between different kinds of entities, but in your use case there will be only one set anyway (the MWEs).

I assume this is sufficient already?
