### ISSUE TITLE
space attribute not implemented according to documentation

### ISSUE THREAD

**Issue by kosloot** [proycon/folia#28]
The FoLiA  documentation states:
Allowed values for space are:
- “yes” or “ ” (a space) – This is the default and says that the token is followed by a single space.
-  “no” or “” (empty) – This states that the token is not followed by a space.
-  any other character or string – This states that the token is followed by another character or string that acts as a token separator.

But both the Python version and the C++ version only implement the boolean value.

I suggest removing the 'any other character or string' case from the documentation, as that has never occurred in this universe

**Comment by proycon** [comment]
Right, agreed

**Comment by kosloot** [comment]
thanx
