### ISSUE TITLE
revise class hierarchy considering paragraphs and sentences

### ISSUE THREAD

**Issue by kosloot** [proycon/folia#42]
At the moment, the accepted data considering sentence and/or paragraph is a bit rigid and unclear

For example: 
A Caption may contain a Sentence, but not a Paragraph. 
But that means that it also may contain several Sentences.
But isn't that just a Paragraph?

An Entry may NOT contain Sentence or Paragraph, but it may contain a Term, which may contain both.

An Utterance may contain a Sentence, but not a Paragraph, which somehow makes sense, but it may contain a Quote too, which accepts both.

The ratio is unclear to me.

**Comment by kosloot** [comment]
This is related to: https://github.com/LanguageMachines/ucto/issues/40

**Comment by proycon** [comment]
I made it a bit more flexible, but that comes at a risk too, something I don't want to allow but which we currently can't enforce yet is a pattern like (xpath): //p/somethingelse/p

**Comment by kosloot** [comment]
Yeah. There are several 'fair use' or 'sensible' policies for FoLiA, but enforcing them can be troublesome.
I'm not sure if DTD's or XmlSchema can rule this.
Otherwise we could implement some run-time checks.
e.g checking whether a `<p>` is embedded directly or indirectly in another `<p>` is not that hard.
Maybe MOST tags cannot be 'recursive'. So maybe we could make a property that allows this for the few that can? `<div>` comes to mind. `<part>` maybe?
