### ISSUE TITLE
AbstractSpanRole needs TEXTCLASS attribute

### ISSUE THREAD

**Issue by kosloot** [proycon/folia#57]
"hd" and "Dependent" nodes are AbstractSpanRole nodes and may NOT have TEXTCLASS.
But they contain WordRefs which are textclass dependent.
Just like entities, which are AbstractSpanAnnotation and MAY have TEXTCLASS

I think this is unbalanced, probably an oversight.

FWIW: Do we need this Role vs. Annotation distinction?

**Comment by proycon** [comment]
I think they should probably inherit their textclass from the parent span annotation, as I don't really see a use case for different textclasses within a single span annotation element.

**Comment by kosloot** [comment]
I solved this (more elegant I think) in libfolia for 2.0. closing this
