### ISSUE TITLE
Rename alignment annotation to relation annotation?

### ISSUE THREAD

**Issue by proycon** [proycon/folia#59]
I'm contemplating renaming *alignment annotation* (see https://folia.readthedocs.io/en/folia2.0/alignment_annotation.html, a form of higher-order annotation) to **relation annotation**, which sounds more generic and far more to the point.

It would require some extra hacks for backward compatibility with the old name.

**Comment by proycon** [comment]
Reference is a a structure annotation element that is an explicit reference in the text, think of things like footnotes and hyperlinks. This is higher-order annotation that can set a relationship between anything.

**Comment by proycon** [comment]
But yes, the terminology might be confusing. This could just as well have been called reference in another parallel universe.

**Comment by kosloot** [comment]
and the one off the reference examples seems (almost) to do what relation does. 
```xml
      <note xml:id="example.note.1" class="footnote">
        <part>
            <t>See our website.</t>
        </part>
        <ref xml:id="example.ref.2" xlink:href="https://github.io/folia" xlink:type="simple" format="text/html" />
      </note>
```

So this has to be explained carefully.  And I fear that users also will loose track.

**Comment by proycon** [comment]
Yes, the documentation has been reworked so it should be clear hopefully. Feel free to judge for yourself: 
https://folia.readthedocs.io/en/folia2.0/reference_annotation.html

**Comment by kosloot** [comment]
is surely much clearer
