### ISSUE TITLE
allow a foreign-annotation node

### ISSUE THREAD

**Issue by kosloot** [proycon/folia#7]
Sometimes you want to ad some 'raw XML' to a FoLiA document.
This then can be serialized. Or you can request a pointer to it. 
FoLiA itself will NOT parse or use this XML.

suggestion: add a <foreign-annotation> node to store raw XML.
the raw XML should NOT be in the FoLiA name-space. 

'alien' nodes that are NOT under such an annotation node are completely ignored and discarded 
(this is the current behaviour)

QUESTIONS:
- should we actively check that the name-space != FoLiA ? probably yes.

- Is the foreign name-space to be defined on the foreign-annotation node or on its immediate child?
 ```
  <foreign-annotation xmlns:pm="http://...">
         <pm:members pm:status="present">
 
```
versus:
   <foreign-annotation>
         <pm:members pm:status="present" xmlns:pm="http://...">

**Comment by proycon** [comment]
The node will be ``foreign-data``, reusing the same one as used in metadata.

**Comment by proycon** [comment]
Closing, documented and implemented in both libraries now
