### ISSUE TITLE
foliavalidator: switch on -t for all v1.5+ documents

### ISSUE THREAD

**Issue by kosloot** [proycon/folia#71]
I was quite surprised by the fact that foliavalidator happily accepted an invalid document I created.
Only after a while, I discovered that textvalidation (-t option) is switched off, even for 2.0 documents.
I think this is wrong. switching on -t for v1.5+ documents should be the default imho.

**Comment by proycon** [comment]
That would be a bug indeed, text validation should be on for all v1.5+ document yes!

**Comment by proycon** [comment]
Reproduced:

```
 $ foliavalidator inconsistenttext.1.5.0.folia.xml
WARNING: Document (inconsistenttext.1.5.0.folia.xml) uses an older FoLiA version (1.5.0) but is validated with a newer library (2.0.1). If this is a document you created and intend to publish, you may want to upgrade this FoLiA v1 document to FoLiA v2 using the 'foliaupgrade' tool.
Validated successfully: inconsistenttext.1.5.0.folia.xm
```
