### ISSUE TITLE
Is a Sentence in a Quote authoriative?

### ISSUE THREAD

**Issue by kosloot** [proycon/folia#82]
in older folia versions, there was code tot set the Sentence to non-authoriative when connected to a Quote.

It seems that more recent FoLiA doesn't have this anymore, but libfolia stil has this.

Should I remove this restriction?

**Comment by proycon** [comment]
Yes, you can remove that. I don't think we use non-authoritativeness in that way anymore (became too complex).

**Comment by kosloot** [comment]
ok, thanx
