### ISSUE TITLE
Ensure example.xml examples are "sensible"

### ISSUE THREAD

**Issue by proycon** [proycon/folia#9]
Try to clean up some of `example.xml` so the examples are semantically sensible. It's not just used by our test suites. The whitespace occurrence for example led to some confusion.

**Comment by proycon** [comment]
@kosloot Perhaps this is something we should consider working on in the near future (for v1.6?), as the example.xml is now getting rather contrived... and it actually makes a poor example and is only suited for our test suite. It would be quite some work since the test suite has to adapt :/

It may also be an idea to tie a new example.xml to automatically generated documentation (#43), killing multiple birds with one stone...

**Comment by kosloot** [comment]
Yeah we really need this.
I suggest to create a range of examples to demonstrate the several 'features' and probably some use cases, like a full-fledged Frog output file, ans a FLAT annotation.
We should also create a NEW example whenever a new feature is added. (incrementing the Frog version accordingly)
Maybe we should keep one rather convoluted example though, to demonstrate/test interference between all kinds of constructs?

**Comment by proycon** [comment]
> I suggest to create a range of examples to demonstrate the several 'features' and probably some use cases, like a full-fledged Frog output file, ans a FLAT annotation.

Yes, agreed

> We should also create a NEW example whenever a new feature is added. (incrementing the Frog version accordingly)

Good idea yes, keeping existing examples as is

> Maybe we should keep one rather convoluted example though, to demonstrate/test interference between all kinds of constructs?

I guess our current ``example.xml`` can take on that role (but we should rename it I guess).

**Comment by proycon** [comment]
This is currently being worked on alongside #43; the examples for the documentation and tests will be shared, preventing unnecessary duplication and allowing stricter validation.

Afterwards the test set for foliapy and libfolia will need to be updated to reference the new examples.
